name: Deploying to Production

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t hiringgo:latest .

      - name: Save Docker image to file
        run: docker save hiringgo:latest -o hiringgo.tar

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST_ARISHA }}
          username: ${{ secrets.SSH_USERNAME_ARISHA }}
          key: ${{ secrets.SSH_KEY_ARISHA }}
          source: "hiringgo.tar"
          target: "~/"

      - name: Load and run Docker image on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST_ARISHA }}
          username: ${{ secrets.SSH_USERNAME_ARISHA }}
          key: ${{ secrets.SSH_KEY_ARISHA }}
          script: |
            docker stop hiringgo || true && docker rm hiringgo || true
            docker load -i ~/hiringgo.tar
            docker run -d \
              --name hiringgo \
              -p 8080:8080 \
              -e SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
              -e SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              hiringgo:latest
