name: Deploying to Production

on:
  push:
    branches:
      - deployment/arisha
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME_ARISHA }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_ARISHA }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME_ARISHA }}/${{ secrets.DOCKER_HUB_REPO_NAME_ARISHA }}:latest

      - name: Releasing New Version
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST_ARISHA }}
          username: ${{ secrets.SSH_USERNAME_ARISHA }}
          key: ${{ secrets.SSH_KEY_ARISHA }}
          script: |
            docker rmi $(docker images -a -q)
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME_ARISHA }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_ARISHA }}
            docker pull ${{ secrets.DOCKER_HUB_USERNAME_ARISHA }}/${{ secrets.DOCKER_HUB_REPO_NAME_ARISHA }}:latest
            source .env
            docker run -d \
            --name=web_server \
            -p 8080:8080 \
            -e ENV1="insert env var anda disini jika perlu" \
            ${{ secrets.DOCKER_HUB_USERNAME_ARISHA }}/${{ secrets.DOCKER_HUB_REPO_NAME_ARISHA }}:latest
