name: Deploying to Production

on:
  workflow_run:
    workflows: ["Unit Tests"]
    types:
      - completed
    branches:
      - main

jobs:
  if: ${{ github.event.workflow_run.conclusion == 'success' }}
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy project files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "~/app"

      - name: Build and run Docker on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/app
            docker stop hiringgo || true && docker rm hiringgo || true
            docker build -t hiringgo .
            docker run -d \
              --name hiringgo \
              -p 8080:8080 \
              -e SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
              -e SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              hiringgo
